if ! git diff-index --quiet HEAD --; then git stash push -q -m "pr-create"; PR_URL=$(gh pr create --base 'phase/5-orchestrator-hardening' --head 'fix/174' --title 'fix(cli): prevent subagents from clobbering root state.json within worktrees' --body 'The Quality Gate subagent'\''s manual smoke testing commands (e.g., `bin/agyloop plan --issue 999`) were initializing a new pipeline state while inside isolated worktrees. Due to the `.agyloop` directory being symlinked back to the repository root, this polluted the shared global state, overwriting the active issue context.

This adds a strict guard in `FileStateRepository.save()` to detect if the CLI is running inside a worktree using `IssueNumber.inferFromPath(process.cwd())`. If a mismatch between the worktree'\''s inferred issue and the state snapshot'\''s issue is detected, a `StateStorageError` is thrown, preventing cross-issue state corruption.

Closes #174'); echo "$PR_URL"; PR_NUM=$(echo "$PR_URL" | grep -oE '[0-9]+$'); if [ -n "$PR_NUM" ]; then gh issue close 174 --comment 'Implemented and merged via PR #'"$PR_NUM"' into `phase/5-orchestrator-hardening`.'; fi; git stash pop -q; else PR_URL=$(gh pr create --base 'phase/5-orchestrator-hardening' --head 'fix/174' --title 'fix(cli): prevent subagents from clobbering root state.json within worktrees' --body 'The Quality Gate subagent'\''s manual smoke testing commands (e.g., `bin/agyloop plan --issue 999`) were initializing a new pipeline state while inside isolated worktrees. Due to the `.agyloop` directory being symlinked back to the repository root, this polluted the shared global state, overwriting the active issue context.

This adds a strict guard in `FileStateRepository.save()` to detect if the CLI is running inside a worktree using `IssueNumber.inferFromPath(process.cwd())`. If a mismatch between the worktree'\''s inferred issue and the state snapshot'\''s issue is detected, a `StateStorageError` is thrown, preventing cross-issue state corruption.

Closes #174'); echo "$PR_URL"; PR_NUM=$(echo "$PR_URL" | grep -oE '[0-9]+$'); if [ -n "$PR_NUM" ]; then gh issue close 174 --comment 'Implemented and merged via PR #'"$PR_NUM"' into `phase/5-orchestrator-hardening`.'; fi; fi
